# Generated by Django 4.0.4 on 2022-05-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product_of', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='product.product')),
            ],
        ),
    ]
